checks:
    php: true

filter:
    excluded_paths: [vendor/*, tests/*, app/Console/*, app/Exeptions/*, app/Providers/*, public/*, phpdoc/*, report/*]

build:
    environment:
        php: 7.1.12

    project_setup:
        before:
            - "make prepare"
            - "mkdir builds"
            - "php artisan config:cache"
            - "mysql -uroot -e 'CREATE DATABASE test'"
            - "mysql -uroot test < database/sql/grouper.sql"

    tests:
        stop_on_failure: true
        override:
            -
                command: "make test"
                coverage:
                    file: "builds/coverage.clover"
                    format: "php-clover"
