checks:
    php: true

filter:
    excluded_paths: [vendor/*, tests/*, app/Console/*, app/Exeptions/*, app/Providers/*, public/*, phpdoc/*, report/*]

build:
    environment:
        mysql: 5.5
        php: 7.1.12

    project_setup:
        before:
            - "make prepare"
            - "mkdir build"
            - mysql -uroot -e 'CREATE DATABASE grouper'
            - mysql -uroot grouper < database/sql/grouper.sql

    tests:
        override:
            -
                command: "./vendor/bin/phpunit --configuration phpunit.xml"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"
