filter:
    excluded_paths: [vendor/*, tests/*, app/Console/*, app/Exeptions/*, app/Providers/*, public/*, phpdoc/*, report/*]

build:
    environment:
        php:
            version: 7.1
    tests:
        override:
            -
                command: ./vendor/phpunit/phpunit/phpunit
